### ISSUE TITLE
Format profile and codec ID are not reflected in rendered file

### ISSUE THREAD

**Issue by ambustion** [UDaManFunks/prores_encoder#2]
In testing out quality differences, I am seeing that encoded files always default to having metadata tagged as format profile: 422 and codec ID apcn, regardless of which format is rendered. They do appear to be rendering the correct bitrates however.

**Comment by UDaManFunks** [comment]
Thanks for the feedback.  The problem seems to be that one can't "override" the property 'pIOPropFourCC' once it's set to s_RegisterCodecs (and it can't be omitted either) in "DoInit", or "DoOpen".   The 4 PRORES profiles have different fourCC codes (listed below) unlike other codecs 

apch | Apple ProRes 422 (HQ)
apcn | Apple ProRes 422
apco | Apple ProRes 422 (Proxy)
apcs | Apple ProRes 422 (LT)

If one can't override it in DoInit or DoOpen, it would mean that I'd have to create 4 different plugins instead - each one registering a different 'pIOPropFourCC' in s_RegisterCodec for that specific profile which sucks.   Maybe it'll be something DR supports in the future.

Documentation is lacking from DR which is another issue.

**Comment by ambustion** [comment]
Understood thank you for looking into it.

**Comment by UDaManFunks** [comment]
I thought about it in a different way and implemented each "profile" as a CODEC instead.    I quickly modified it to support prores422 and prores422-HQ which can be selected in the "codec" portion of the export screen instead of the "plugin settings".

Looks like it's setting the correct fourCC code now in the export file.    Let me know if it's working for you as well and i'll add codecs for the "PROXY" and "LT"

**Comment by UDaManFunks** [comment]
> Understood thank you for looking into it.

I thought about it in a different way and implemented each "profile" as a CODEC instead.  If you git clone it again and rebuild the plugin, you'll notice that the export codec portion will have different options.  Looks like it's setting the correct fourCC code now in the export file.

I'm learning as I go along, hopefully this will sample code will help people write their own DR export codecs in the future (or wrap more of FFMPEGs export codecs).

**Comment by ambustion** [comment]
Yes! Works great on this end. All of the metadata  is correct in there and I think setting it from that dropdown is more intuitive anyway. I think this is a great example for other people, I know I learned a lot poking around but I only know python so definitely out of my league to contribute at this point. I also compared to duplicate renders from a mac and the bitrate was within a couple Mb/s so very close. Speed was about realtime for all of them, compared to about 10 second render for a 2 minute test  h265 to prores encode on apple silicon but some speed difference is definitely expected.
